-- 코드를 작성해주세요
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY

FROM ITEM_INFO i 
JOIN ITEM_TREE t1 ON i.ITEM_ID = t1.ITEM_ID
LEFT JOIN ITEM_TREE t2 ON t1.ITEM_ID = t2.PARENT_ITEM_ID

WHERE t2.ITEM_ID IS NULL

ORDER BY ITEM_ID DESC;